---
- hosts: all

  vars:
    kbs:
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: clearcompressionflag.exe
      - guid: D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A
        filename: Windows8.1-KB2919442-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2919355-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2932046-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2959977-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2937592-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2938439-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2934018-x64.msu
      - guid: D/1/3/D13E3150-3BB2-4B22-9D8A-47EE2D609FFF
        filename: Windows8.1-KB2999226-x64.msu

  tasks:
    - name: "Install tools"
      win_chocolatey:
        name: "{{ item }}"
        allow_empty_checksums: "yes"
      with_items:
        - googlechrome

    - name: Install pre-req Windows updates
      include: install-kb.yml
      with_items: "{{ kbs }}"
      tags: kbs

    - name: "Enable Remote Desktop"
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: "Open Remote Desktop in firewall"
      win_firewall_rule:
        name: "remote desktop"
        enable: yes
        state: present
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        force: true